import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";
import { FlotingNavbar } from "./component/FlotingNavbar";
import CustomCursor from "./component/courser";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], // Select Required Weights
  variable: "--font-poppins", // CSS Variable
});

export const metadata: Metadata = {
  title: "Taha Najam - Freelance Graphic Designer - UK & USA",
  description: "Generated by Muhammad Maaz",
  icons: "/images/favicon.ico", // Favicon set as apple-icon
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased cursor-none`}>
        <CustomCursor />
        <Navbar />
        <FlotingNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
